apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-kub
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-kub
  template:
    metadata:
      labels:
        app: node-app-kub
    spec:
      containers:
      - name: nod-app-kub
        image: glutenfree69/node-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: default

spec:
  type: LoadBalancer
  selector:
    app: node-app-kub
  ports:
    - port: 80 
      targetPort: 8000 
